### ISSUE TITLE
サインイン画面 カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#10]

**Comment by takashi0602** [comment]
![s__211419143](https://user-images.githubusercontent.com/30039352/34076090-490dcb5c-e31e-11e7-9640-b8b148623516.jpg)

**Comment by tyokinuhata** [comment]
今回はめんどくさいので標準のサインイン/サインアップだけでいいかなとおもっている

**Comment by takashi0602** [comment]
![s__211492871](https://user-images.githubusercontent.com/30039352/34079968-bb3d9426-e37a-11e7-8eca-5811d286a1b7.jpg)
