### ISSUE TITLE
サインアップ画面 カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#11]

**Comment by takashi0602** [comment]
![s__211419142](https://user-images.githubusercontent.com/30039352/34076098-5f9372fa-e31e-11e7-894e-7e3a383d071f.jpg)

**Comment by tyokinuhata** [comment]
今回はめんどくさいので標準のサインイン/サインアップだけでいいかなとおもっている

「登録する」はボタンみたいな感じでお願い

**Comment by takashi0602** [comment]
![s__211492872](https://user-images.githubusercontent.com/30039352/34079974-cba0e480-e37a-11e7-8f2e-fdc9dcbf83c4.jpg)
