### ISSUE TITLE
チャット画面 カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#12]

**Comment by takashi0602** [comment]
![s__209960966](https://user-images.githubusercontent.com/30039352/33769447-a13fe812-dc6d-11e7-9ded-ce937ecfd982.jpg)

**Comment by tyokinuhata** [comment]
ジャンルというかタグみたいなのをつけれるようにしたいかも

あといいね機能は廃止してルームのお気に入り機能を追加で

投稿画面は左右の余白0にしてフッターみたいな感じにしてちょ

**Comment by takashi0602** [comment]
![s__211427330](https://user-images.githubusercontent.com/30039352/34076099-6fac5a9e-e31e-11e7-94ad-0a4f77849ab6.jpg)

**Comment by tyokinuhata** [comment]
細かいけどタグは四角で囲むようにしようかなあ

**Comment by takashi0602** [comment]
![s__211492867](https://user-images.githubusercontent.com/30039352/34079977-dc3eabc4-e37a-11e7-927e-c174a1147764.jpg)
