### ISSUE TITLE
テーマカラー

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#14]
テーマカラー(５色ほど)のカラーコードとその色の画像をおねがい

**Comment by takashi0602** [comment]
- #AB4238
<img width="101" alt="2017-12-17 23 59 55" src="https://user-images.githubusercontent.com/30039352/34080784-b3497940-e386-11e7-85b4-e2d6ed6299a0.png">

- #489E7C
<img width="100" alt="2017-12-18 0 00 29" src="https://user-images.githubusercontent.com/30039352/34080787-bca40c76-e386-11e7-89e3-ec53de3cc3d4.png">

- #287CAC
<img width="100" alt="2017-12-18 0 09 53" src="https://user-images.githubusercontent.com/30039352/34080866-e1876780-e387-11e7-8aa0-9f4377f04fe5.png">

- #F7F711
<img width="100" alt="2017-12-18 0 17 35" src="https://user-images.githubusercontent.com/30039352/34080917-e5053de6-e388-11e7-9ae4-e61c38f90a33.png">

- #7755F1
<img width="100" alt="2017-12-18 0 19 34" src="https://user-images.githubusercontent.com/30039352/34080943-36984c70-e389-11e7-97dd-04c9bd583242.png">

**Comment by tyokinuhata** [comment]
赤、緑メインで他三色はところどころって感じで行きましょう
