### ISSUE TITLE
チャット(ルーム)検索画面 カンプ作成

### ISSUE THREAD

**Issue by takashi0602** [AfterSchoolStudy/chat-mammoth#15]

**Comment by takashi0602** [comment]
![s__209960967](https://user-images.githubusercontent.com/30039352/33769425-897c382a-dc6d-11e7-97bf-0f86ca7ab0a5.jpg)

**Comment by tyokinuhata** [comment]
ルーム検索はルーム毎にルームIDを割り当ててそれで検索できるようにしようかな(楽そうなので)

**Comment by takashi0602** [comment]
![s__211419140](https://user-images.githubusercontent.com/30039352/34076103-88a77394-e31e-11e7-9e24-5e35e42d9320.jpg)

**Comment by tyokinuhata** [comment]
ページネーションにするかさらに読み込むにするかは要相談って感じやな

**Comment by takashi0602** [comment]
![s__211492868](https://user-images.githubusercontent.com/30039352/34079992-f353c858-e37a-11e7-921e-9ba3cb4b9daa.jpg)
