### ISSUE TITLE
チャット(ルーム)作成画面

### ISSUE THREAD

**Issue by takashi0602** [AfterSchoolStudy/chat-mammoth#16]

**Comment by takashi0602** [comment]
![s__209960969](https://user-images.githubusercontent.com/30039352/33769589-18abd32a-dc6e-11e7-8f3a-1971ade516ea.jpg)

**Comment by tyokinuhata** [comment]
ジャンル選択 -> タグの追加(なんか適当にFLSとか参考に...)

それとpublic/privateの選択もできるようにお願い

privateにした場合、あいことばてきなやつを設定できるように

**Comment by takashi0602** [comment]
![s__211419141](https://user-images.githubusercontent.com/30039352/34076108-a548061c-e31e-11e7-93f5-c0c2bcea1dbb.jpg)

**Comment by tyokinuhata** [comment]
ルームを作成します -> ルーム作成 に文言修正

タグを四角に

「ルームを作成」をボタン的な感じに

**Comment by takashi0602** [comment]
![s__211492870](https://user-images.githubusercontent.com/30039352/34079999-ff7de19a-e37a-11e7-8da5-a2475ffafe80.jpg)
