### ISSUE TITLE
ヘッダー

### ISSUE THREAD

**Issue by takashi0602** [AfterSchoolStudy/chat-mammoth#17]

**Comment by takashi0602** [comment]
![s__209960963](https://user-images.githubusercontent.com/30039352/33769642-5026f9d8-dc6e-11e7-8631-7ad38d2766be.jpg)

**Comment by tyokinuhata** [comment]
メニューの詳細をお願いします

**Comment by takashi0602** [comment]
- サインイン
- サインアップ
- トップページ
- ルーム検索
- マイページ(サインインした場合)
- ルーム作成(サインインした場合)
- サインアウト(サインインした場合)

**Comment by tyokinuhata** [comment]
レスポンシブ対応にして画面幅を狭めたときにハンバーガーメニューが出るってこと？

それなら画面幅最大時のヘッダーをみたいかも

**Comment by takashi0602** [comment]
レスポンシブした時にハンバーガーメニュー出るってことであってます。
![s__211558402](https://user-images.githubusercontent.com/30039352/34081094-b3b1656e-e38b-11e7-8b0f-06abf8126f25.jpg)
