### ISSUE TITLE
Privateルーム モーダル

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#18]
Privateルームを開いたときのあいことばを入力させるモーダルのカンプ

**Comment by takashi0602** [comment]
![s__211419144](https://user-images.githubusercontent.com/30039352/34076111-b1d11cd4-e31e-11e7-9c30-d8215ad54baf.jpg)

**Comment by tyokinuhata** [comment]
入力 -> OK に文言修正

右上の☓は削除で

**Comment by takashi0602** [comment]
![s__211550212](https://user-images.githubusercontent.com/30039352/34080727-056aab64-e386-11e7-8527-b9d57cac5ce5.jpg)
