### ISSUE TITLE
サインアップ画面カンプ修正

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#48]
サインアップ画面のフォームの項目を

- スクリーンネーム
- ID
- パスワード
- パスワード(確認)

に修正する

**Comment by takashi0602** [comment]
![s__212467719](https://user-images.githubusercontent.com/30039352/34455776-a4e6c6f8-edc9-11e7-865f-b6f9d4e88889.jpg)

**Comment by tyokinuhata** [comment]
完成
