### ISSUE TITLE
サインイン画面 カンプ修正

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#53]
サインイン画面の項目を

- ID
- パスワード

にする

- パスワードを記憶する のチェックボックスを追加する

**Comment by takashi0602** [comment]
![s__212467720](https://user-images.githubusercontent.com/30039352/34455777-a7c13e30-edc9-11e7-8473-7a3c4175fc96.jpg)

**Comment by tyokinuhata** [comment]
- パスワードを記憶する のチェックボックス

を追加してほしい

**Comment by takashi0602** [comment]
![s__212475907](https://user-images.githubusercontent.com/30039352/34455876-cbddfa90-edcb-11e7-9e8d-c72d0a58a803.jpg)

**Comment by tyokinuhata** [comment]
完成
