### ISSUE TITLE
マイページ カンプ修正

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#59]
ルーム名の横にタグ、下にルームの説明を追加

さらに読み込むをページネーションにする

**Comment by takashi0602** [comment]
![s__212467721](https://user-images.githubusercontent.com/30039352/34455778-a9ebe854-edc9-11e7-94ed-6b41af499bf1.jpg)

**Comment by tyokinuhata** [comment]
完成
