### ISSUE TITLE
チャットページ カンプ修正

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#60]
お気に入りに追加のチェックボックスを☆にする

さらに読み込むを削除する(直近n件を表示するようにするため)

**Comment by takashi0602** [comment]
![s__212467722](https://user-images.githubusercontent.com/30039352/34455787-d108a1a2-edc9-11e7-8d69-376713a8d98f.jpg)

**Comment by tyokinuhata** [comment]
完成
