### ISSUE TITLE
チャットルーム検索ページ カンプ修正

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#64]
チャットルーム検索ページのカンプに以下を追加お願いします

- 検索結果が０件の場合
- 検索ボタンを押す前の状態

**Comment by takashi0602** [comment]
デフォルト
![s__212467725](https://user-images.githubusercontent.com/30039352/34455794-fd8e8764-edc9-11e7-8084-c135c74e70cb.jpg)
検索成功
![s__212467724](https://user-images.githubusercontent.com/30039352/34455795-014ff40a-edca-11e7-8645-b6ec7047dc74.jpg)
検索失敗
![s__212467723](https://user-images.githubusercontent.com/30039352/34455796-04b17812-edca-11e7-8ee1-48dcba21031d.jpg)

**Comment by tyokinuhata** [comment]
- 該当するチャットルームが見つかりませんでした.

に修正

**Comment by takashi0602** [comment]
![s__212475908](https://user-images.githubusercontent.com/30039352/34455875-c9402600-edcb-11e7-82fe-b283e4b4b3cc.jpg)

**Comment by tyokinuhata** [comment]
完成
