### ISSUE TITLE
トップ画面カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#8]
figmaかinVision使ってみても良いよ

**Comment by takashi0602** [comment]
![s__209960964](https://user-images.githubusercontent.com/30039352/33769537-ed46ceec-dc6d-11e7-9cb9-4cc00f82ce2e.jpg)

**Comment by tyokinuhata** [comment]
@takashi0602 
キャッチフレーブ -> キャッチフレーズに修正

使い方は消してそこにチャットルームの選択画面が表示されるように変更お願いします

**Comment by takashi0602** [comment]
![s__211419138](https://user-images.githubusercontent.com/30039352/34076086-3325cbb4-e31e-11e7-8f26-350b65042720.jpg)

**Comment by tyokinuhata** [comment]
ルーム名の下に説明欄(n文字を超えたら...にする)を作って欲しいかも

**Comment by takashi0602** [comment]
![s__211492873](https://user-images.githubusercontent.com/30039352/34079957-8509a1f6-e37a-11e7-985a-14add7e0fe62.jpg)

**Comment by tyokinuhata** [comment]
あ、ごめん

チャットルームを探すもボタンにしてちょ

**Comment by takashi0602** [comment]
![s__211550211](https://user-images.githubusercontent.com/30039352/34080713-cb29755c-e385-11e7-8c31-7f9d2b8f7101.jpg)
