### ISSUE TITLE
マイページ カンプ作成

### ISSUE THREAD

**Issue by tyokinuhata** [AfterSchoolStudy/chat-mammoth#9]

**Comment by takashi0602** [comment]
![s__209960968](https://user-images.githubusercontent.com/30039352/33769478-b9222fb2-dc6d-11e7-97d6-f3d461cd0c87.jpg)

**Comment by tyokinuhata** [comment]
マイページは
- スクリーンネーム
- ユーザID
- そのユーザが作ったチャットルーム
を表示するように変更

その他お気に入り登録したチャットルームの表示などに修正お願いします。

コメント数、いいね数、閲覧履歴は削除で

**Comment by takashi0602** [comment]
![s__211460099](https://user-images.githubusercontent.com/30039352/34076576-e4452bfa-e32e-11e7-8020-943e99636d85.jpg)

**Comment by tyokinuhata** [comment]
SPAにしたときページネーションがなあって感じはあるなあ

もっと読み込むてきな感じにするか
